# yaml-language-server: $schema=https://json-schema.org/draft/2019-09/schema#

version: '3.0'
services:
  db:
    image: postgres
    restart: unless-stopped
    container_name: integration-tests-prisma
    ports:
      - "5437:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Alvinle292001
      POSTGRES_DB: tests